import type { Lineup, PitchingStaff } from '../types';
import html2canvas from 'html2canvas';

export function exportLineupAsText(
  lineup: Lineup,
  pitchingStaff?: PitchingStaff | null,
): string {
  const modeLabel = {
    general: 'General',
    vs_rhp: 'vs RHP',
    vs_lhp: 'vs LHP',
    defense: 'Best Defense',
    balanced: 'Balanced',
  }[lineup.type] ?? lineup.type;

  const lines: string[] = [];
  lines.push(`=== OOTP Lineup: ${modeLabel} ===`);
  lines.push(`OFF: ${lineup.totalOffense.toFixed(1)} | DEF: ${lineup.totalDefense.toFixed(1)}`);
  lines.push('');

  // Batting Order
  lines.push('Batting Order:');
  lineup.battingOrder.forEach((slot, i) => {
    const num = String(i + 1).padStart(2, ' ');
    const pos = slot.position.padEnd(3);
    const name = slot.player.name.padEnd(22);
    const off = slot.player.scores.offensiveScore.toFixed(0);
    lines.push(` ${num}. (${pos}) ${name} OFF: ${off}`);
  });
  lines.push('');

  // Field Positions
  lines.push('Field Positions:');
  lineup.slots.forEach((slot) => {
    const pos = slot.position.padEnd(3);
    const name = slot.player.name.padEnd(22);
    const score = slot.score.toFixed(0);
    const oop = slot.outOfPosition ? ' *OOP' : '';
    lines.push(` ${pos} | ${name} Score: ${score}${oop}`);
  });

  // Bench
  if (lineup.bench.length > 0) {
    lines.push('');
    lines.push('Bench:');
    lineup.bench.forEach((p) => {
      const name = p.name.padEnd(22);
      const positions = p.eligiblePositions.join('/');
      lines.push(` - ${name} (${positions}) OVR: ${p.scores.overallValue.toFixed(0)}`);
    });
  }

  // Pitching Staff
  if (pitchingStaff) {
    lines.push('');
    lines.push('--- Pitching Staff ---');
    if (pitchingStaff.rotation.length > 0) {
      lines.push('Rotation:');
      pitchingStaff.rotation.forEach((p, i) => {
        lines.push(` SP${i + 1}: ${p.name.padEnd(22)} Score: ${p.scores.starterScore.toFixed(0)}`);
      });
    }
    if (pitchingStaff.closer) {
      lines.push(`CL:   ${pitchingStaff.closer.name.padEnd(22)} Score: ${pitchingStaff.closer.scores.relieverScore.toFixed(0)}`);
    }
    if (pitchingStaff.setupMen.length > 0) {
      lines.push('Setup:');
      pitchingStaff.setupMen.forEach((p) => {
        lines.push(` SU:  ${p.name.padEnd(22)} Score: ${p.scores.relieverScore.toFixed(0)}`);
      });
    }
    if (pitchingStaff.longReliever) {
      lines.push(`LR:   ${pitchingStaff.longReliever.name.padEnd(22)} Score: ${pitchingStaff.longReliever.scores.relieverScore.toFixed(0)}`);
    }
    if (pitchingStaff.middleRelievers.length > 0) {
      lines.push('Middle Relief:');
      pitchingStaff.middleRelievers.forEach((p) => {
        lines.push(` MR:  ${p.name.padEnd(22)} Score: ${p.scores.relieverScore.toFixed(0)}`);
      });
    }
  }

  lines.push('');
  lines.push('Generated by OOTP Roster Analyzer');

  return lines.join('\n');
}

export async function exportLineupAsImage(elementId: string): Promise<void> {
  const element = document.getElementById(elementId);
  if (!element) return;

  const canvas = await html2canvas(element, {
    backgroundColor: '#030712',
    scale: 2,
  });

  const link = document.createElement('a');
  link.download = 'ootp-lineup.png';
  link.href = canvas.toDataURL('image/png');
  link.click();
}
